### ISSUE TITLE
ERR: frame length greater than maximum allowed (2301 vs 2048) and increasing

### ISSUE THREAD

**Issue by t3therdev** [aler9/rtsp-simple-server#229]
## Which version are you using?

v0.14.2

## Which operating system are you using?

OS

- [ ] Linux
- [x] Windows
- [ ] macOS

## Describe the issue

When using version 0.14.2 and doing a proxy of another rtsp stream, we are getting the errror:

ERR: frame length greater than maximum allowed (2301 vs 2048)
each error increases and just disconnects. There are some references to his in other bugs.

`2021/03/06 01:15:00 [I] [0/0/0] rtsp-simple-server v0.14.2
2021/03/06 01:15:00 [I] [0/0/0] [TCP/RTSP listener] opened on 10.168.1.97:8554
2021/03/06 01:15:00 [I] [0/0/0] [path ch1] [rtsp source] started
2021/03/06 01:15:00 [I] [0/0/0] [path ch1] [rtsp source] connecting
2021/03/06 01:15:00 [I] [0/0/0] [path ch1] [rtsp source] ready
2021/03/06 01:15:02 [I] [0/0/0] [path ch1] [rtsp source] ERR: frame length greater than maximum allowed (3485 vs 2048)
2021/03/06 01:15:07 [I] [0/0/0] [path ch1] [rtsp source] connecting
2021/03/06 01:15:07 [I] [0/0/0] [path ch1] [rtsp source] ready
2021/03/06 01:15:08 [I] [0/0/0] [path ch1] [rtsp source] ERR: frame length greater than maximum allowed (7361 vs 2048)
2021/03/06 01:15:13 [I] [0/0/0] [path ch1] [rtsp source] connecting
2021/03/06 01:15:13 [I] [0/0/0] [path ch1] [rtsp source] ready
2021/03/06 01:15:14 [I] [0/0/0] [path ch1] [rtsp source] ERR: frame length greater than maximum allowed (5234 vs 2048)
2021/03/06 01:15:19 [I] [0/0/0] [path ch1] [rtsp source] connecting
2021/03/06 01:15:19 [I] [0/0/0] [path ch1] [rtsp source] ready
2021/03/06 01:15:20 [I] [0/0/0] [path ch1] [rtsp source] ERR: frame length greater than maximum allowed (3821 vs 2048)
2021/03/06 01:15:25 [I] [0/0/0] [path ch1] [rtsp source] connecting
2021/03/06 01:15:25 [I] [0/0/0] [path ch1] [rtsp source] ready
2021/03/06 01:15:26 [I] [0/0/0] [path ch1] [rtsp source] ERR: frame length greater than maximum allowed (2187 vs 2048)
`

## Describe how to replicate the issue

1. start the server

2. Publish with:
paths:
  ch1:
    source: rtsp://user:pass@serveripaddress:6201/1
Protocol is tcp
3. errors in console, can't stay connected.

**Comment by t3therdev** [comment]
tried increasing this as well:

readBufferCount: 2048 (tried different values)

**Comment by t3therdev** [comment]
Tried a different camera. Had to change it from tcp to udp to avoid the issue. Now its not giving errors (2nd type of camera) but it doesn't proxy the stream. 

`2021/03/06 11:55:50 [I] [0/0/0] [path ch1] [rtsp source] started
2021/03/06 11:55:50 [I] [0/0/0] [path ch1] [rtsp source] stopped
2021/03/06 11:55:50 [I] [0/0/0] [path ch1] [rtsp source] connecting
2021/03/06 11:55:50 [I] [0/0/0] [path ch1] [rtsp source] ready
2021/03/06 11:55:56 [I] [1/0/0] [client 10.168.1.97:58982] connected (plain)
2021/03/06 11:55:56 [I] [1/0/1] [client 10.168.1.97:58982] is reading from path 'ch1', 1 track with udp
2021/03/06 11:56:15 [I] [1/0/1] [client 10.168.1.97:58982] ERR: read tcp 10.168.1.97:8554->10.168.1.97:58982: wsarecv: A`

**Comment by t3therdev** [comment]
Hi @aler9 any suggestions on this?

**Comment by t3therdev** [comment]
This issue is still present in v0.15.0

**Comment by dorinclisu** [comment]
I don't understand, this issue was already solved in v0.14.1-6-ga938554, see https://github.com/aler9/rtsp-simple-server/issues/211#issuecomment-784348518

**Comment by t3therdev** [comment]
This is still an issue even in 0.15.4. Increasing the readBufferSize doesn't seem to help. 
Are we saying that the NALU fragmentation is causing this? Is there not a way to handle it?

**Comment by aler9** [comment]
> This is still an issue even in 0.15.4. Increasing the readBufferSize doesn't seem to help.
> Are we saying that the NALU fragmentation is causing this? Is there not a way to handle it?

Increasing readBufferSize does solve the issue, anyway it's not the proper way to handle this - it's just a workaround to support a non-standard situation.

NALUs can have any size, but, in order to be sent with RTSP (or WebRTC) they must be fragmented into multiple RTP packets. Each RTP packet cannot have a size greater than 1472 bytes, that means that every NALU fragment contained inside a RTP packet must not exceed 1460 bytes.

RTP packets with a size greater than 1460 bytes are not received correctly in every situation.

Instructions on how to perform the fragmentation are described in rfc/rtp/h264:

https://tools.ietf.org/html/rfc6184#page-29

It's not the server responsibility to perform the fragmentation, the source is responsible for doing this.
