### ISSUE TITLE
Ondemand proxy stream start/stop every 10 seconds

### ISSUE THREAD

**Issue by clee604** [aler9/rtsp-simple-server#949]
## Which version are you using?

v0.18.3 and v0.18.4 seems to be affected, v0.18.2 works fine

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [x ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I use rtsp-simple-server to proxy some home webcam feeds to save wifi bandwidth and to prevent overload of the camera when there are multiple clients connected to it. Since 0.18.3+, the proxy stream seems to destroyed and recreated every 10 seconds. I've rolled back to 0.18.2 and this works fine. I've tested this using docker on both an amd64 and arm7 device connected by ethernet. 

## Describe how to replicate the issue

I upgraded from my 0.18.2 docker container to both 0.18.3 and 0.18.4 via recreating the container but pointing to same configuration file.

I use the following path config with my credentials and ip omitted. The camera in question is an Eufy indoor cam but I've tried it with my wyze and other rtsp cameras with the same results.

paths:
   eufy:
    source: rtsp://[user]:[password]@[local cam ip]/live0
    sourceOnDemand: yes

I am accessing the rtsp proxy feed using TinyCam, via TCP RTSP.

## Did you attach the server logs?

I looked through both the debug and info logs and didn't see any errors. But the info log does seem to imply it is related to the 10 second time out.

2022/05/20 04:15:46 INF rtsp-simple-server v0.18.4

2022/05/20 04:15:46 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)

2022/05/20 04:15:46 INF [RTMP] listener opened on :1935

2022/05/20 04:15:46 INF [HLS] listener opened on :8888

2022/05/20 04:15:57 INF [RTSP] [conn [ip omitted]:44790] opened

2022/05/20 04:15:57 INF [path eufy] [rtsp source] started

2022/05/20 04:15:57 INF [path eufy] [rtsp source] ready

2022/05/20 04:15:57 INF [RTSP] [session 805985855] created by [ip omitted]:44790

2022/05/20 04:15:57 INF [RTSP] [session 805985855] is reading from path 'eufy', 1 track with TCP

2022/05/20 04:16:07 INF [path eufy] [rtsp source] stopped

2022/05/20 04:16:07 INF [RTSP] [conn [ip omitted]:44790] closed (terminated)

2022/05/20 04:16:07 INF [RTSP] [session 805985855] destroyed (terminated)

2022/05/20 04:16:07 INF [RTSP] [conn [ip omitted]:44826] opened

2022/05/20 04:16:07 INF [path eufy] [rtsp source] started

2022/05/20 04:16:08 INF [path eufy] [rtsp source] ready

2022/05/20 04:16:08 INF [RTSP] [session 609575719] created by [ip omitted]:44826

2022/05/20 04:16:08 INF [RTSP] [session 609575719] is reading from path 'eufy', 1 track with TCP

2022/05/20 04:16:18 INF [path eufy] [rtsp source] stopped

2022/05/20 04:16:18 INF [RTSP] [conn [ip omitted]:44826] closed (terminated)

2022/05/20 04:16:18 INF [RTSP] [session 609575719] destroyed (terminated)

2022/05/20 04:16:18 INF [RTSP] [conn [ip omitted]:44878] opened

2022/05/20 04:16:18 INF [path eufy] [rtsp source] started

2022/05/20 04:16:18 INF [path eufy] [rtsp source] ready

2022/05/20 04:16:18 INF [RTSP] [session 988193212] created by [ip omitted]:44878

2022/05/20 04:16:18 INF [RTSP] [session 988193212] is reading from path 'eufy', 1 track with TCP

2022/05/20 04:16:28 INF [path eufy] [rtsp source] stopped

2022/05/20 04:16:28 INF [RTSP] [conn [ip omitted]:44878] closed (terminated)

2022/05/20 04:16:28 INF [RTSP] [session 988193212] destroyed (terminated)

2022/05/20 04:16:28 INF [RTSP] [conn [ip omitted]:45014] opened

2022/05/20 04:16:28 INF [path eufy] [rtsp source] started

2022/05/20 04:16:28 INF [path eufy] [rtsp source] ready

2022/05/20 04:16:28 INF [RTSP] [session 555739947] created by [ip omitted]:45014

2022/05/20 04:16:28 INF [RTSP] [session 555739947] is reading from path 'eufy', 1 track with TCP

2022/05/20 04:16:38 INF [path eufy] [rtsp source] stopped

2022/05/20 04:16:38 INF [RTSP] [conn [ip omitted]:45014] closed (terminated)

2022/05/20 04:16:38 INF [RTSP] [session 555739947] destroyed (terminated)

2022/05/20 04:16:38 INF [RTSP] [conn [ip omitted]:45136] opened

2022/05/20 04:16:38 INF [path eufy] [rtsp source] started

2022/05/20 04:16:38 INF [path eufy] [rtsp source] ready

2022/05/20 04:16:38 INF [RTSP] [session 574926904] created by [ip omitted]:45136

2022/05/20 04:16:38 INF [RTSP] [session 574926904] is reading from path 'eufy', 1 track with TCP

2022/05/20 04:16:41 INF [RTSP] [conn [ip omitted]:45136] closed (terminated)

2022/05/20 04:16:41 INF [RTSP] [session 574926904] destroyed (teared down by [ip omitted]:45136)

## Did you attach a network dump?

no

**Comment by rapi3** [comment]
+1
The same problem on RPI3 and Intel x64 running Ubuntu 20.04.4 LTS.
all my CCTV streams are in this format:
readUser: yyyyy
readPass: xxxxx
source: rtsp://....
sourceOnDemand: yes
sourceOnDemandCloseAfter: 20s

I use celluloid and vlc on linux with network cache 3s.
The stream stop after few seconds with v0.18.4.
I did not tested v0.18.3 just try to update from v0.18.2 that works OK and reverted back very quick.

**Comment by necrobala** [comment]
+1
We are facing the same problem.
The stream is active till the sourceOnDemandCloseAfter duration

**Comment by tompointexe** [comment]
+1

**Comment by aler9** [comment]
Sorry for the regression, this has been fixed in main and a new release will be published ASAP.
In the meanwhile you can use this nightly release:
[rtsp-simple-server_v0.18.4-1-g23ac079_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8744700/rtsp-simple-server_v0.18.4-1-g23ac079_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.18.4-1-g23ac079_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8744702/rtsp-simple-server_v0.18.4-1-g23ac079_linux_amd64.tar.gz)
[rtsp-simple-server_v0.18.4-1-g23ac079_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8744703/rtsp-simple-server_v0.18.4-1-g23ac079_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.18.4-1-g23ac079_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8744704/rtsp-simple-server_v0.18.4-1-g23ac079_linux_armv6.tar.gz)
[rtsp-simple-server_v0.18.4-1-g23ac079_linux_armv7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8744706/rtsp-simple-server_v0.18.4-1-g23ac079_linux_armv7.tar.gz)
[rtsp-simple-server_v0.18.4-1-g23ac079_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/8744708/rtsp-simple-server_v0.18.4-1-g23ac079_windows_amd64.zip)

**Comment by 0ip** [comment]
With a config like that, even with version `v0.18.4-1-g23ac079`, I still have the problem 
```
paths:
  foo:
    source: rtsp://bar
    sourceOnDemand: yes
    sourceProtocol: "tcp"
```

**Comment by aler9** [comment]
added in v0.18.5. Please open another issue if the problem persists.

**Comment by NickSurin** [comment]
You fixed for sourceOnDemand but for runOnDemand problem still exists.

**Comment by aler9** [comment]
@NickSurin please open another issue and provide a precise way to replicate.
